### ISSUE TITLE
Game ended without saying Game Over or something else 

### ISSUE THREAD

**Issue by SahilSinghTomar** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#22]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to **not become a wizard** but then **game ended**
![Screenshot_20230310_103840](https://user-images.githubusercontent.com/50849361/224229958-eac7050f-3000-43a3-b3f2-320de4fa886b.png)

### Release version

I am running it locally.

### Steps to reproduce

1.  while taking right
2. talking to stranger
3. not becoming the wizard
4. Game Ended

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by KendallDoesCoding** [comment]
@SahilSinghTomar There was a small error in the code it should be fixed now.

Also, please run pip install -r requirements.txt to get colors for text, get music etc.

**Comment by KendallDoesCoding** [comment]
Or just run git pull and run the project again, it will automatically download the modules you don't have installed from v0.8.0

**Comment by SahilSinghTomar** [comment]
ok thank u

**Comment by SahilSinghTomar** [comment]
Issue is still not fixed
![not_fixed](https://user-images.githubusercontent.com/50849361/224273328-2d8b98c2-687e-4367-9499-144f06651d27.png)


# I can fix it 

## I have sent a PR. Please review and tell me it is correct or not.

**Comment by KendallDoesCoding** [comment]
@SahilSinghTomar You deleted the message where you said issue was not fixed? I think you hadn't git pulled so it wasn't updated for you locally, right?

**Comment by SahilSinghTomar** [comment]
@KendallDoesCoding I pulled already.
it is already up to date

```python
def chapter_stranger():
    answer = input(Fore.GREEN +
        "You cross the bridge and meet a stranger, do you talk to them? (y/n) " + Fore.LIGHTMAGENTA_EX).lower()
    if answer == "n":
        game_over(Fore.RED + "The stranger was not pleased by you and murdered you. \U0001F480")
    elif answer == "y":
        answer = input(Fore.GREEN +
            "You talk a wizard and they ask you,"
            "do you want to be a wizard? (y/n) " + Fore.LIGHTMAGENTA_EX).lower()
        if answer == "y":
            game_over(Fore.RED + "You are a wizard and you WIN the game! \U0001f3c6", win=True)
```

we have to add another **elif** statement after last if statement for answer == "n"

to become a wizard or not question should also have a elif statement
for correct functioning.

**Comment by SahilSinghTomar** [comment]
You have to add another elif statement after last statement

```python
elif answer == "n":
        game_over(Fore.RED + "The stranger was not pleased by you and murdered you. \U0001F480")
```
So, that game will be over if user asked not to become wizard.
Am i Right??

**Comment by SahilSinghTomar** [comment]
If you wish i can add these changes and a random feature in my next PR.

**Comment by KendallDoesCoding** [comment]
Well, when it's elif the message doesn't display for me, if it's if answer ==n then the message displays for me?

Does the message display for you or no after pulling? coz it displays for me.

Which OS do you use?

**Comment by KendallDoesCoding** [comment]
I think maybe coz your using Linux it doesn't work?

**Comment by SahilSinghTomar** [comment]
![not_fixed](https://user-images.githubusercontent.com/50849361/224291003-475d9205-474e-4bcc-8e41-dfbabc959a60.png)

**Comment by SahilSinghTomar** [comment]
@KendallDoesCoding can u send yours screen shot.

**Comment by SahilSinghTomar** [comment]
After adding elif
```python
def chapter_stranger():
    answer = input(Fore.GREEN +
        "You cross the bridge and meet a stranger, do you talk to them? (y/n) " + Fore.LIGHTMAGENTA_EX).lower()
    if answer == "n":
        game_over(Fore.RED + "The stranger was not pleased by you and murdered you. \U0001F480")
    elif answer == "y":
        answer = input(Fore.GREEN +
            "You talk a wizard and they ask you,"
            "do you want to be a wizard? (y/n) " + Fore.LIGHTMAGENTA_EX).lower()
        if answer == "y":
            game_over(Fore.RED + "You are a wizard and you WIN the game! \U0001f3c6", win=True)
        elif answer == "n":
            game_over(Fore.RED + "The stranger was not pleased by you and murdered you. \U0001F480")
```
![works](https://user-images.githubusercontent.com/50849361/224292436-e4b27e2d-1b60-41aa-911c-10bc460d343c.png)

It works just Fine

**Comment by KendallDoesCoding** [comment]
Oh, it works. Please make a Pull-request. Thanks!

The way it is right now, works for me but not for you.

**Comment by KendallDoesCoding** [comment]
if you download the v0.7.2 it is fixed, versions after that it isn't fixed. it will be fixed in the latest version when I make a release.

I don't want to make a release now as it'll be a duplicate of v0.7.2.

Thanks for your help.
